name: dotnet-core-sdk:3.1
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Docker build
        uses: docker/build-push-action@v1
        env:
          DOCKER_PUSH: false
          DOCKER_PUSH_TEST: ${{ contains(github.ref, '3.1') }}
          BRANCH_TEST: ${{ env.github.ref }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: khayes/dotnet-core-sdk
          tags: 3.1
          push: ${{ env.DOCKER_PUSH }}
          dockerfile: ./dotnet-core-sdk/3.1/Dockerfile